### ISSUE TITLE
highlight-defined doesn't override rainbow-identifiers face

### ISSUE THREAD

**Issue by a13** [Fanael/highlight-defined#1]
Hi!

It looks like highlight-defined (called from emacs-lisp-mode-hook) doesn't fontify keywords that were fontified before by rainbow-identifiers (called from prog-mode-hook)

**Comment by Fanael** [comment]
What happens if you order them the other way around, i.e. first start highlight-defined, then rainbow-identifiers?

**Comment by a13** [comment]
In that order everything works ok. The thing is I can't find a simple way to make them loading in that order, because emacs-lisp-mode is derived from prog-mode and loads its hooks after it.

**Comment by Fanael** [comment]
You should be able to do
```emacs-lisp
(highlight-defined-mode)
(rainbow-identifiers-mode)
```
in your `emacs-lisp-mode-hook` function.

**Comment by a13** [comment]
Yeeeah, man, thanks!

```org
(use-package rainbow-identifiers
       :hook
       (emacs-lisp-mode . rainbow-identifiers-mode)
       (prog-mode . rainbow-identifiers-mode))
```

fixed this issue for me!
