### ISSUE TITLE
Highlight generalized variables?

### ISSUE THREAD

**Issue by clemera** [Fanael/highlight-defined#4]
In [this](https://www.reddit.com/r/emacs/comments/ikgfxd/weekly_tipstricketc_thread/g3nss2u/) discussion I realized I often overlook the opportunity to use generalized place forms and think it would be nice to highlight symbols which can be used with a distinct face. WDYT?

**Comment by clemera** [comment]
On a further note I think it would be nice to be able to configure which type of symbols one would like to highlight with this package.

**Comment by Fanael** [comment]
This package is essentially unmaintained; if you know how to implement this feature and are willing to maintain it, I can transfer the ownership of the repository.

**Comment by alphapapa** [comment]
@clemera We could also consider implementing it in https://github.com/alphapapa/highlight-function-calls

**Comment by clemera** [comment]
Oh, I should have expected you also have a fitting package in your arsenal ;) I would prefer that over becoming a maintainer of this package but thanks for your offer @Fanael.
